# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/qt_designer/ui_button_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_button_widget(object):
    def setupUi(self, button_widget):
        button_widget.setObjectName("button_widget")
        button_widget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(button_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(button_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.submit_button = QtWidgets.QPushButton(self.frame)
        self.submit_button.setMinimumSize(QtCore.QSize(0, 30))
        self.submit_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}\n"
"")
        self.submit_button.setObjectName("submit_button")
        self.horizontalLayout.addWidget(self.submit_button)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(button_widget)
        QtCore.QMetaObject.connectSlotsByName(button_widget)

    def retranslateUi(self, button_widget):
        _translate = QtCore.QCoreApplication.translate
        button_widget.setWindowTitle(_translate("button_widget", "Form"))
        self.submit_button.setText(_translate("button_widget", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    button_widget = QtWidgets.QWidget()
    ui = Ui_button_widget()
    ui.setupUi(button_widget)
    button_widget.show()
    sys.exit(app.exec_())
