# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/qt_designer/ui_category_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_category_widget(object):
    def setupUi(self, category_widget):
        category_widget.setObjectName("category_widget")
        category_widget.resize(400, 253)
        category_widget.setMinimumSize(QtCore.QSize(200, 0))
        self.horizontalLayout = QtWidgets.QHBoxLayout(category_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(category_widget)
        self.frame.setStyleSheet("background-color:#FDF8F5;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.category_name = QtWidgets.QPushButton(self.frame_3)
        self.category_name.setStyleSheet("QPushButton {\n"
"    color:#4F4846;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"")
        self.category_name.setObjectName("category_name")
        self.horizontalLayout_3.addWidget(self.category_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.color_button = QtWidgets.QPushButton(self.frame_3)
        self.color_button.setMinimumSize(QtCore.QSize(30, 30))
        self.color_button.setMaximumSize(QtCore.QSize(30, 30))
        self.color_button.setStyleSheet("QPushButton {\n"
"    color:#4F4846;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 2px;\n"
"    background-color:#4F4846;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid;\n"
"}\n"
"")
        self.color_button.setText("")
        self.color_button.setObjectName("color_button")
        self.horizontalLayout_3.addWidget(self.color_button)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.category_table = QtWidgets.QTableWidget(self.frame_2)
        self.category_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.category_table.setColumnCount(4)
        self.category_table.setObjectName("category_table")
        self.category_table.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.category_table)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(category_widget)
        QtCore.QMetaObject.connectSlotsByName(category_widget)

    def retranslateUi(self, category_widget):
        _translate = QtCore.QCoreApplication.translate
        category_widget.setWindowTitle(_translate("category_widget", "Form"))
        self.category_name.setText(_translate("category_widget", "⏵Category Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    category_widget = QtWidgets.QWidget()
    ui = Ui_category_widget()
    ui.setupUi(category_widget)
    category_widget.show()
    sys.exit(app.exec_())
