# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/qt_designer/ui_login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(600, 450)
        login_window.setMinimumSize(QtCore.QSize(600, 450))
        login_window.setMaximumSize(QtCore.QSize(600, 450))
        self.central_widget = QtWidgets.QWidget(login_window)
        self.central_widget.setAutoFillBackground(False)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stacked_widget = QtWidgets.QStackedWidget(self.central_widget)
        self.stacked_widget.setStyleSheet("background-color:#FDF8F5;")
        self.stacked_widget.setObjectName("stacked_widget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.login_page)
        self.verticalLayout_2.setContentsMargins(11, -1, -1, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.login_title_frame = QtWidgets.QFrame(self.login_page)
        self.login_title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_title_frame.setObjectName("login_title_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.login_title_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_label = QtWidgets.QLabel(self.login_title_frame)
        self.login_label.setMinimumSize(QtCore.QSize(588, 50))
        self.login_label.setMaximumSize(QtCore.QSize(588, 50))
        self.login_label.setStyleSheet("QLabel {\n"
"    font: bold 30px;\n"
"    color:#4F4846;\n"
"}")
        self.login_label.setObjectName("login_label")
        self.horizontalLayout.addWidget(self.login_label)
        self.verticalLayout_2.addWidget(self.login_title_frame)
        self.username_frame = QtWidgets.QFrame(self.login_page)
        self.username_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username_frame.setObjectName("username_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.username_frame)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.username_label = QtWidgets.QLabel(self.username_frame)
        self.username_label.setMinimumSize(QtCore.QSize(100, 0))
        self.username_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.username_label.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.username_label.setObjectName("username_label")
        self.horizontalLayout_2.addWidget(self.username_label)
        self.username_field = QtWidgets.QLineEdit(self.username_frame)
        self.username_field.setMinimumSize(QtCore.QSize(250, 25))
        self.username_field.setMaximumSize(QtCore.QSize(25, 16777215))
        self.username_field.setStyleSheet("QLineEdit {\n"
"    font: 15px;\n"
"}")
        self.username_field.setObjectName("username_field")
        self.horizontalLayout_2.addWidget(self.username_field)
        self.verticalLayout_2.addWidget(self.username_frame)
        self.password_frame = QtWidgets.QFrame(self.login_page)
        self.password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.password_frame.setObjectName("password_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.password_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.password_label = QtWidgets.QLabel(self.password_frame)
        self.password_label.setMinimumSize(QtCore.QSize(100, 0))
        self.password_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.password_label.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.password_label.setObjectName("password_label")
        self.horizontalLayout_3.addWidget(self.password_label)
        self.password_field = QtWidgets.QLineEdit(self.password_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_field.sizePolicy().hasHeightForWidth())
        self.password_field.setSizePolicy(sizePolicy)
        self.password_field.setMinimumSize(QtCore.QSize(250, 25))
        self.password_field.setMaximumSize(QtCore.QSize(250, 25))
        self.password_field.setStyleSheet("QLineEdit {\n"
"    font: 15px;\n"
"}")
        self.password_field.setObjectName("password_field")
        self.horizontalLayout_3.addWidget(self.password_field)
        self.verticalLayout_2.addWidget(self.password_frame)
        self.bottom_frame = QtWidgets.QFrame(self.login_page)
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.to_signup_button = QtWidgets.QPushButton(self.bottom_frame)
        self.to_signup_button.setMinimumSize(QtCore.QSize(100, 30))
        self.to_signup_button.setMaximumSize(QtCore.QSize(100, 30))
        self.to_signup_button.setStyleSheet("QPushButton {\n"
"    color:blue;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"")
        self.to_signup_button.setObjectName("to_signup_button")
        self.horizontalLayout_4.addWidget(self.to_signup_button)
        self.login_button = QtWidgets.QPushButton(self.bottom_frame)
        self.login_button.setMinimumSize(QtCore.QSize(100, 30))
        self.login_button.setMaximumSize(QtCore.QSize(100, 30))
        self.login_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}")
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_4.addWidget(self.login_button)
        self.verticalLayout_2.addWidget(self.bottom_frame)
        self.stacked_widget.addWidget(self.login_page)
        self.sign_up_page = QtWidgets.QWidget()
        self.sign_up_page.setStyleSheet("")
        self.sign_up_page.setObjectName("sign_up_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sign_up_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.signup_title_frame = QtWidgets.QFrame(self.sign_up_page)
        self.signup_title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signup_title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signup_title_frame.setObjectName("signup_title_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.signup_title_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.signup_label = QtWidgets.QLabel(self.signup_title_frame)
        self.signup_label.setStyleSheet("QLabel {\n"
"    font: bold 30px;\n"
"    color:#4F4846;\n"
"}")
        self.signup_label.setObjectName("signup_label")
        self.horizontalLayout_5.addWidget(self.signup_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.signup_title_frame)
        self.username_frame1 = QtWidgets.QFrame(self.sign_up_page)
        self.username_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username_frame1.setObjectName("username_frame1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.username_frame1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.username_label1 = QtWidgets.QLabel(self.username_frame1)
        self.username_label1.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.username_label1.setObjectName("username_label1")
        self.horizontalLayout_6.addWidget(self.username_label1)
        self.username_field1 = QtWidgets.QLineEdit(self.username_frame1)
        self.username_field1.setObjectName("username_field1")
        self.horizontalLayout_6.addWidget(self.username_field1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.username_frame1)
        self.password_frame1 = QtWidgets.QFrame(self.sign_up_page)
        self.password_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.password_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.password_frame1.setObjectName("password_frame1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.password_frame1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.password_label1 = QtWidgets.QLabel(self.password_frame1)
        self.password_label1.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.password_label1.setObjectName("password_label1")
        self.horizontalLayout_7.addWidget(self.password_label1)
        self.password_field1 = QtWidgets.QLineEdit(self.password_frame1)
        self.password_field1.setObjectName("password_field1")
        self.horizontalLayout_7.addWidget(self.password_field1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.password_frame1)
        self.confirm_frame1 = QtWidgets.QFrame(self.sign_up_page)
        self.confirm_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.confirm_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.confirm_frame1.setObjectName("confirm_frame1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.confirm_frame1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.confirm_label1 = QtWidgets.QLabel(self.confirm_frame1)
        self.confirm_label1.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.confirm_label1.setObjectName("confirm_label1")
        self.horizontalLayout_8.addWidget(self.confirm_label1)
        self.confirm_field1 = QtWidgets.QLineEdit(self.confirm_frame1)
        self.confirm_field1.setObjectName("confirm_field1")
        self.horizontalLayout_8.addWidget(self.confirm_field1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.confirm_frame1)
        self.email_frame1 = QtWidgets.QFrame(self.sign_up_page)
        self.email_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.email_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.email_frame1.setObjectName("email_frame1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.email_frame1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.email_label1 = QtWidgets.QLabel(self.email_frame1)
        self.email_label1.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.email_label1.setObjectName("email_label1")
        self.horizontalLayout_9.addWidget(self.email_label1)
        self.email_field1 = QtWidgets.QLineEdit(self.email_frame1)
        self.email_field1.setObjectName("email_field1")
        self.horizontalLayout_9.addWidget(self.email_field1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.email_frame1)
        self.bottom_frame1 = QtWidgets.QFrame(self.sign_up_page)
        self.bottom_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame1.setObjectName("bottom_frame1")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.bottom_frame1)
        self.horizontalLayout_10.setSpacing(100)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.to_login_button = QtWidgets.QPushButton(self.bottom_frame1)
        self.to_login_button.setMinimumSize(QtCore.QSize(150, 30))
        self.to_login_button.setMaximumSize(QtCore.QSize(100, 30))
        self.to_login_button.setStyleSheet("QPushButton {\n"
"    color:blue;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"")
        self.to_login_button.setObjectName("to_login_button")
        self.horizontalLayout_10.addWidget(self.to_login_button)
        self.signup_button = QtWidgets.QPushButton(self.bottom_frame1)
        self.signup_button.setMinimumSize(QtCore.QSize(100, 30))
        self.signup_button.setMaximumSize(QtCore.QSize(100, 30))
        self.signup_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}")
        self.signup_button.setObjectName("signup_button")
        self.horizontalLayout_10.addWidget(self.signup_button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.bottom_frame1)
        self.stacked_widget.addWidget(self.sign_up_page)
        self.verticalLayout.addWidget(self.stacked_widget)
        login_window.setCentralWidget(self.central_widget)

        self.retranslateUi(login_window)
        self.stacked_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "MainWindow"))
        self.login_label.setText(_translate("login_window", "       Login:"))
        self.username_label.setText(_translate("login_window", "Username:"))
        self.password_label.setText(_translate("login_window", "Password:"))
        self.to_signup_button.setText(_translate("login_window", "Sign Up"))
        self.login_button.setText(_translate("login_window", "Login"))
        self.signup_label.setText(_translate("login_window", "Sign Up:"))
        self.username_label1.setText(_translate("login_window", "Username:"))
        self.password_label1.setText(_translate("login_window", "Password:"))
        self.confirm_label1.setText(_translate("login_window", "Confirm Password:"))
        self.email_label1.setText(_translate("login_window", "Email:"))
        self.to_login_button.setText(_translate("login_window", "Back to login"))
        self.signup_button.setText(_translate("login_window", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_window = QtWidgets.QMainWindow()
    ui = Ui_login_window()
    ui.setupUi(login_window)
    login_window.show()
    sys.exit(app.exec_())
