# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/qt_designer/ui_label_field_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_label_widget(object):
    def setupUi(self, label_widget):
        label_widget.setObjectName("label_widget")
        label_widget.resize(400, 300)
        label_widget.setStyleSheet("QFrame {\n"
"background-color:#FDF8F5;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(label_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(label_widget)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setStyleSheet("QLabel {\n"
"    font: 16px;\n"
"    color:#4F4846;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.verticalLayout.addWidget(self.frame_8)

        self.retranslateUi(label_widget)
        QtCore.QMetaObject.connectSlotsByName(label_widget)

    def retranslateUi(self, label_widget):
        _translate = QtCore.QCoreApplication.translate
        label_widget.setWindowTitle(_translate("label_widget", "Form"))
        self.label_4.setText(_translate("label_widget", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    label_widget = QtWidgets.QWidget()
    ui = Ui_label_widget()
    ui.setupUi(label_widget)
    label_widget.show()
    sys.exit(app.exec_())
