# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/qt_designer/ui_label_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_text_field_widget(object):
    def setupUi(self, text_field_widget):
        text_field_widget.setObjectName("text_field_widget")
        text_field_widget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(text_field_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(text_field_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_edit = QtWidgets.QLineEdit(self.frame)
        self.label_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.label_edit.setStyleSheet("font: 16px;")
        self.label_edit.setObjectName("label_edit")
        self.horizontalLayout.addWidget(self.label_edit)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(text_field_widget)
        QtCore.QMetaObject.connectSlotsByName(text_field_widget)

    def retranslateUi(self, text_field_widget):
        _translate = QtCore.QCoreApplication.translate
        text_field_widget.setWindowTitle(_translate("text_field_widget", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    text_field_widget = QtWidgets.QWidget()
    ui = Ui_text_field_widget()
    ui.setupUi(text_field_widget)
    text_field_widget.show()
    sys.exit(app.exec_())
