# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/qt_designer/password_manager_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(987, 695)
        main_window.setMinimumSize(QtCore.QSize(700, 400))
        main_window.setStyleSheet("")
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_frame = QtWidgets.QFrame(self.central_widget)
        self.menu_frame.setMinimumSize(QtCore.QSize(300, 0))
        self.menu_frame.setStyleSheet("QFrame {\n"
"    background-color:#FDF8F5;\n"
"}")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu_button_frame = QtWidgets.QFrame(self.menu_frame)
        self.menu_button_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.menu_button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_button_frame.setLineWidth(1)
        self.menu_button_frame.setObjectName("menu_button_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menu_button_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menu_toggle_button = QtWidgets.QPushButton(self.menu_button_frame)
        self.menu_toggle_button.setMinimumSize(QtCore.QSize(0, 40))
        self.menu_toggle_button.setStyleSheet("QPushButton {\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}")
        self.menu_toggle_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/gui/qt_designer\\icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_toggle_button.setIcon(icon)
        self.menu_toggle_button.setObjectName("menu_toggle_button")
        self.horizontalLayout_2.addWidget(self.menu_toggle_button)
        self.verticalLayout.addWidget(self.menu_button_frame)
        self.menu_password_frame = QtWidgets.QFrame(self.menu_frame)
        self.menu_password_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.menu_password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_password_frame.setObjectName("menu_password_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menu_password_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menu_password_button = QtWidgets.QPushButton(self.menu_password_frame)
        self.menu_password_button.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_password_button.setStyleSheet("QPushButton {\n"
"    color:#DDAF94;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#FDF8F5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        self.menu_password_button.setFlat(False)
        self.menu_password_button.setObjectName("menu_password_button")
        self.horizontalLayout_3.addWidget(self.menu_password_button)
        self.verticalLayout.addWidget(self.menu_password_frame)
        self.menu_group_frame = QtWidgets.QFrame(self.menu_frame)
        self.menu_group_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_group_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_group_frame.setObjectName("menu_group_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.menu_group_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_group_button = QtWidgets.QPushButton(self.menu_group_frame)
        self.menu_group_button.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_group_button.setStyleSheet("QPushButton {\n"
"    color:#DDAF94;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#FDF8F5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        self.menu_group_button.setObjectName("menu_group_button")
        self.horizontalLayout_4.addWidget(self.menu_group_button)
        self.verticalLayout.addWidget(self.menu_group_frame)
        self.menu_security_frame = QtWidgets.QFrame(self.menu_frame)
        self.menu_security_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_security_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_security_frame.setObjectName("menu_security_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.menu_security_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.menu_security_button = QtWidgets.QPushButton(self.menu_security_frame)
        self.menu_security_button.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_security_button.setStyleSheet("QPushButton {\n"
"    color:#DDAF94;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#FDF8F5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        self.menu_security_button.setObjectName("menu_security_button")
        self.horizontalLayout_5.addWidget(self.menu_security_button)
        self.verticalLayout.addWidget(self.menu_security_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.menu_info_frame = QtWidgets.QFrame(self.menu_frame)
        self.menu_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_info_frame.setObjectName("menu_info_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.menu_info_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.menu_profile_button = QtWidgets.QPushButton(self.menu_info_frame)
        self.menu_profile_button.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_profile_button.setStyleSheet("QPushButton {\n"
"    color:#DDAF94;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#FDF8F5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        self.menu_profile_button.setObjectName("menu_profile_button")
        self.horizontalLayout_6.addWidget(self.menu_profile_button)
        self.menu_settings_button = QtWidgets.QPushButton(self.menu_info_frame)
        self.menu_settings_button.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_settings_button.setMaximumSize(QtCore.QSize(16777215, 60))
        self.menu_settings_button.setStyleSheet("QPushButton {\n"
"    color:#DDAF94;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#FDF8F5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}\n"
"")
        self.menu_settings_button.setObjectName("menu_settings_button")
        self.horizontalLayout_6.addWidget(self.menu_settings_button)
        self.verticalLayout.addWidget(self.menu_info_frame)
        self.horizontalLayout.addWidget(self.menu_frame)
        self.content_frame = QtWidgets.QFrame(self.central_widget)
        self.content_frame.setStyleSheet("QFrame {\n"
"    background-color:#FDF8F5;\n"
"}")
        self.content_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stacked_widget = QtWidgets.QStackedWidget(self.content_frame)
        self.stacked_widget.setObjectName("stacked_widget")
        self.password_page = QtWidgets.QWidget()
        self.password_page.setObjectName("password_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.password_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_frame = QtWidgets.QFrame(self.password_page)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setStyleSheet("QLabel {\n"
"    font: bold 30px;\n"
"    color:#4F4846;\n"
"}")
        self.title_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_7.addWidget(self.title_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.title_frame)
        self.heading_line = QtWidgets.QFrame(self.password_page)
        self.heading_line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.heading_line.setStyleSheet("color:#4F4846;")
        self.heading_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.heading_line.setLineWidth(10)
        self.heading_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.heading_line.setObjectName("heading_line")
        self.verticalLayout_3.addWidget(self.heading_line)
        self.header_frame = QtWidgets.QFrame(self.password_page)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_8.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.new_password_button = QtWidgets.QPushButton(self.header_frame)
        self.new_password_button.setMinimumSize(QtCore.QSize(65, 30))
        self.new_password_button.setMaximumSize(QtCore.QSize(65, 30))
        self.new_password_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}\n"
"")
        self.new_password_button.setObjectName("new_password_button")
        self.horizontalLayout_8.addWidget(self.new_password_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.search_field = QtWidgets.QLineEdit(self.header_frame)
        self.search_field.setMinimumSize(QtCore.QSize(200, 25))
        self.search_field.setMaximumSize(QtCore.QSize(300, 25))
        self.search_field.setStyleSheet("QLineEdit {\n"
"    font: 15px;\n"
"}")
        self.search_field.setObjectName("search_field")
        self.horizontalLayout_8.addWidget(self.search_field)
        self.search_button = QtWidgets.QPushButton(self.header_frame)
        self.search_button.setMinimumSize(QtCore.QSize(40, 30))
        self.search_button.setStyleSheet("QPushButton {\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}")
        self.search_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/gui/qt_designer\\icons/magnifying_glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon1)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_8.addWidget(self.search_button)
        self.verticalLayout_3.addWidget(self.header_frame)
        self.scroll_area = QtWidgets.QScrollArea(self.password_page)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_contents = QtWidgets.QWidget()
        self.scroll_contents.setGeometry(QtCore.QRect(0, 0, 663, 547))
        self.scroll_contents.setObjectName("scroll_contents")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.scroll_contents)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.password_list = QtWidgets.QListWidget(self.scroll_contents)
        self.password_list.setObjectName("password_list")
        self.horizontalLayout_10.addWidget(self.password_list)
        self.scroll_area.setWidget(self.scroll_contents)
        self.verticalLayout_3.addWidget(self.scroll_area)
        self.stacked_widget.addWidget(self.password_page)
        self.group_page = QtWidgets.QWidget()
        self.group_page.setObjectName("group_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.group_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.group_page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4.addWidget(self.frame)
        self.stacked_widget.addWidget(self.group_page)
        self.verticalLayout_2.addWidget(self.stacked_widget)
        self.horizontalLayout.addWidget(self.content_frame)
        main_window.setCentralWidget(self.central_widget)

        self.retranslateUi(main_window)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Password Manager"))
        self.menu_password_button.setText(_translate("main_window", "Passwords"))
        self.menu_group_button.setText(_translate("main_window", "Groups"))
        self.menu_security_button.setText(_translate("main_window", "Security"))
        self.menu_profile_button.setText(_translate("main_window", "Profile"))
        self.menu_settings_button.setText(_translate("main_window", "Settings"))
        self.title_label.setText(_translate("main_window", "Passwords"))
        self.new_password_button.setText(_translate("main_window", "New"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
