# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/qt_designer/ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1148, 838)
        main_window.setMinimumSize(QtCore.QSize(828, 400))
        main_window.setStyleSheet("")
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_frame = QtWidgets.QFrame(self.central_widget)
        self.menu_frame.setMinimumSize(QtCore.QSize(350, 0))
        self.menu_frame.setStyleSheet("QFrame {\n"
"    background-color:#DDAF94;\n"
"    border: 0px solid red;\n"
"}")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu_button_frame = QtWidgets.QFrame(self.menu_frame)
        self.menu_button_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.menu_button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_button_frame.setLineWidth(1)
        self.menu_button_frame.setObjectName("menu_button_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.menu_button_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.menu_toggle_button = QtWidgets.QPushButton(self.menu_button_frame)
        self.menu_toggle_button.setMinimumSize(QtCore.QSize(0, 50))
        self.menu_toggle_button.setMaximumSize(QtCore.QSize(16777215, 50))
        self.menu_toggle_button.setStyleSheet("QPushButton {\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}")
        self.menu_toggle_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/gui/qt_designer\\../../../../../../Users/aaron/.designer/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_toggle_button.setIcon(icon)
        self.menu_toggle_button.setIconSize(QtCore.QSize(50, 50))
        self.menu_toggle_button.setObjectName("menu_toggle_button")
        self.verticalLayout_6.addWidget(self.menu_toggle_button)
        self.line = QtWidgets.QFrame(self.menu_button_frame)
        self.line.setAutoFillBackground(False)
        self.line.setStyleSheet("background-color:#4F4846;")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.verticalLayout.addWidget(self.menu_button_frame)
        self.menu_password_frame = QtWidgets.QFrame(self.menu_frame)
        self.menu_password_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.menu_password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_password_frame.setObjectName("menu_password_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menu_password_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menu_password_button = QtWidgets.QPushButton(self.menu_password_frame)
        self.menu_password_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.menu_password_button.setFont(font)
        self.menu_password_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"    text-align:left;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#DDAF94;\n"
"    padding-left:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/gui/qt_designer\\../../../../../../Users/aaron/.designer/icons/icons8-password-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_password_button.setIcon(icon1)
        self.menu_password_button.setFlat(False)
        self.menu_password_button.setObjectName("menu_password_button")
        self.horizontalLayout_3.addWidget(self.menu_password_button)
        self.verticalLayout.addWidget(self.menu_password_frame)
        self.menu_group_frame = QtWidgets.QFrame(self.menu_frame)
        self.menu_group_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_group_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_group_frame.setObjectName("menu_group_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.menu_group_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_group_button = QtWidgets.QPushButton(self.menu_group_frame)
        self.menu_group_button.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_group_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"    text-align:left;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#DDAF94;\n"
"    padding-left:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("src/gui/qt_designer\\../../../../../../Users/aaron/.designer/icons/icons8-group-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_group_button.setIcon(icon2)
        self.menu_group_button.setObjectName("menu_group_button")
        self.horizontalLayout_4.addWidget(self.menu_group_button)
        self.verticalLayout.addWidget(self.menu_group_frame)
        self.menu_security_frame = QtWidgets.QFrame(self.menu_frame)
        self.menu_security_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_security_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_security_frame.setObjectName("menu_security_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.menu_security_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.menu_security_button = QtWidgets.QPushButton(self.menu_security_frame)
        self.menu_security_button.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_security_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"    text-align:left;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#DDAF94;\n"
"    padding-left:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("src/gui/qt_designer\\../../../../../../Users/aaron/.designer/icons/icons8-shield-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_security_button.setIcon(icon3)
        self.menu_security_button.setObjectName("menu_security_button")
        self.horizontalLayout_5.addWidget(self.menu_security_button)
        self.verticalLayout.addWidget(self.menu_security_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.menu_info_frame = QtWidgets.QFrame(self.menu_frame)
        self.menu_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_info_frame.setObjectName("menu_info_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.menu_info_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.menu_profile_button = QtWidgets.QPushButton(self.menu_info_frame)
        self.menu_profile_button.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_profile_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"    text-align:center;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#DDAF94;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("src/gui/qt_designer\\../../../../../../Users/aaron/.designer/icons/icons8-male-user-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_profile_button.setIcon(icon4)
        self.menu_profile_button.setObjectName("menu_profile_button")
        self.horizontalLayout_6.addWidget(self.menu_profile_button)
        self.menu_settings_button = QtWidgets.QPushButton(self.menu_info_frame)
        self.menu_settings_button.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_settings_button.setMaximumSize(QtCore.QSize(16777215, 60))
        self.menu_settings_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"    text-align:center;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#DDAF94;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("src/gui/qt_designer\\../../../../../../Users/aaron/.designer/icons/icons8-settings-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_settings_button.setIcon(icon5)
        self.menu_settings_button.setObjectName("menu_settings_button")
        self.horizontalLayout_6.addWidget(self.menu_settings_button)
        self.verticalLayout.addWidget(self.menu_info_frame)
        self.horizontalLayout.addWidget(self.menu_frame)
        self.content_frame = QtWidgets.QFrame(self.central_widget)
        self.content_frame.setMinimumSize(QtCore.QSize(478, 0))
        self.content_frame.setStyleSheet("QFrame {\n"
"    background-color:#FDF8F5;\n"
"}")
        self.content_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.content_frame.setLineWidth(0)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stacked_widget = QtWidgets.QStackedWidget(self.content_frame)
        self.stacked_widget.setStyleSheet("")
        self.stacked_widget.setObjectName("stacked_widget")
        self.password_page = QtWidgets.QWidget()
        self.password_page.setObjectName("password_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.password_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_frame = QtWidgets.QFrame(self.password_page)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_frame.setStyleSheet("background-color:#266150")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setStyleSheet("QLabel {\n"
"    font: bold 30px;\n"
"    color:#FDF8F5;\n"
"}")
        self.title_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_7.addWidget(self.title_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.title_frame)
        self.heading_line = QtWidgets.QFrame(self.password_page)
        self.heading_line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.heading_line.setStyleSheet("color:#4F4846;")
        self.heading_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.heading_line.setLineWidth(10)
        self.heading_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.heading_line.setObjectName("heading_line")
        self.verticalLayout_3.addWidget(self.heading_line)
        self.frame_2 = QtWidgets.QFrame(self.password_page)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.header_frame = QtWidgets.QFrame(self.frame_2)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 70))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_8.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.new_password_button = QtWidgets.QPushButton(self.header_frame)
        self.new_password_button.setMinimumSize(QtCore.QSize(85, 30))
        self.new_password_button.setMaximumSize(QtCore.QSize(85, 30))
        self.new_password_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}\n"
"")
        self.new_password_button.setObjectName("new_password_button")
        self.horizontalLayout_8.addWidget(self.new_password_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.search_field = QtWidgets.QLineEdit(self.header_frame)
        self.search_field.setMinimumSize(QtCore.QSize(200, 30))
        self.search_field.setMaximumSize(QtCore.QSize(300, 30))
        self.search_field.setStyleSheet("font: 18px")
        self.search_field.setObjectName("search_field")
        self.horizontalLayout_8.addWidget(self.search_field)
        self.search_button = QtWidgets.QPushButton(self.header_frame)
        self.search_button.setMinimumSize(QtCore.QSize(40, 30))
        self.search_button.setStyleSheet("QPushButton {\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}")
        self.search_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("src/gui/qt_designer\\../../../../../../Users/aaron/.designer/icons/magnifying_glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon6)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_8.addWidget(self.search_button)
        self.verticalLayout_7.addWidget(self.header_frame)
        self.new_password_frame = QtWidgets.QFrame(self.frame_2)
        self.new_password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_password_frame.setObjectName("new_password_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.new_password_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.domain_frame = QtWidgets.QFrame(self.new_password_frame)
        self.domain_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.domain_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.domain_frame.setObjectName("domain_frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.domain_frame)
        self.horizontalLayout_11.setSpacing(70)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.domain_label = QtWidgets.QLabel(self.domain_frame)
        self.domain_label.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.domain_label.setObjectName("domain_label")
        self.horizontalLayout_11.addWidget(self.domain_label)
        self.domain_field = QtWidgets.QLineEdit(self.domain_frame)
        self.domain_field.setMinimumSize(QtCore.QSize(200, 0))
        self.domain_field.setMaximumSize(QtCore.QSize(600, 16777215))
        self.domain_field.setStyleSheet("font: 18px")
        self.domain_field.setObjectName("domain_field")
        self.horizontalLayout_11.addWidget(self.domain_field)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.domain_frame)
        self.account_frame = QtWidgets.QFrame(self.new_password_frame)
        self.account_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.account_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.account_frame.setObjectName("account_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.account_frame)
        self.horizontalLayout_12.setSpacing(20)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.account_label = QtWidgets.QLabel(self.account_frame)
        self.account_label.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.account_label.setObjectName("account_label")
        self.horizontalLayout_12.addWidget(self.account_label)
        self.account_field = QtWidgets.QLineEdit(self.account_frame)
        self.account_field.setMinimumSize(QtCore.QSize(200, 0))
        self.account_field.setMaximumSize(QtCore.QSize(600, 400))
        self.account_field.setStyleSheet("font: 18px")
        self.account_field.setObjectName("account_field")
        self.horizontalLayout_12.addWidget(self.account_field)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_5.addWidget(self.account_frame)
        self.url_frame = QtWidgets.QFrame(self.new_password_frame)
        self.url_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.url_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.url_frame.setObjectName("url_frame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.url_frame)
        self.horizontalLayout_13.setSpacing(110)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.url_label = QtWidgets.QLabel(self.url_frame)
        self.url_label.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.url_label.setObjectName("url_label")
        self.horizontalLayout_13.addWidget(self.url_label)
        self.url_field = QtWidgets.QLineEdit(self.url_frame)
        self.url_field.setMinimumSize(QtCore.QSize(200, 0))
        self.url_field.setMaximumSize(QtCore.QSize(600, 16777215))
        self.url_field.setStyleSheet("font: 18px")
        self.url_field.setObjectName("url_field")
        self.horizontalLayout_13.addWidget(self.url_field)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.verticalLayout_5.addWidget(self.url_frame)
        self.password_frame = QtWidgets.QFrame(self.new_password_frame)
        self.password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.password_frame.setObjectName("password_frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.password_frame)
        self.horizontalLayout_14.setSpacing(53)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.password_label = QtWidgets.QLabel(self.password_frame)
        self.password_label.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.password_label.setObjectName("password_label")
        self.horizontalLayout_14.addWidget(self.password_label)
        self.password_field = QtWidgets.QLineEdit(self.password_frame)
        self.password_field.setMinimumSize(QtCore.QSize(200, 0))
        self.password_field.setMaximumSize(QtCore.QSize(600, 16777215))
        self.password_field.setStyleSheet("font: 18px")
        self.password_field.setObjectName("password_field")
        self.horizontalLayout_14.addWidget(self.password_field)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.verticalLayout_5.addWidget(self.password_frame)
        self.p_category_frame = QtWidgets.QFrame(self.new_password_frame)
        self.p_category_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p_category_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p_category_frame.setObjectName("p_category_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.p_category_frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.p_category_label = QtWidgets.QLabel(self.p_category_frame)
        self.p_category_label.setMinimumSize(QtCore.QSize(150, 0))
        self.p_category_label.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.p_category_label.setObjectName("p_category_label")
        self.horizontalLayout_9.addWidget(self.p_category_label)
        self.p_category_dropdown = QtWidgets.QComboBox(self.p_category_frame)
        self.p_category_dropdown.setMinimumSize(QtCore.QSize(225, 0))
        self.p_category_dropdown.setMaximumSize(QtCore.QSize(225, 16777215))
        self.p_category_dropdown.setStyleSheet("font: 18px")
        self.p_category_dropdown.setObjectName("p_category_dropdown")
        self.horizontalLayout_9.addWidget(self.p_category_dropdown)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_5.addWidget(self.p_category_frame)
        self.add_error_frame = QtWidgets.QFrame(self.new_password_frame)
        self.add_error_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_error_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_error_frame.setObjectName("add_error_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.add_error_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_error_label = QtWidgets.QLabel(self.add_error_frame)
        self.add_error_label.setStyleSheet("QLabel {\n"
"    font: bold 12px;\n"
"    color:#fa9487;\n"
"}")
        self.add_error_label.setObjectName("add_error_label")
        self.horizontalLayout_2.addWidget(self.add_error_label)
        self.verticalLayout_5.addWidget(self.add_error_frame)
        self.add_password_button = QtWidgets.QPushButton(self.new_password_frame)
        self.add_password_button.setMinimumSize(QtCore.QSize(160, 30))
        self.add_password_button.setMaximumSize(QtCore.QSize(160, 30))
        self.add_password_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}\n"
"")
        self.add_password_button.setObjectName("add_password_button")
        self.verticalLayout_5.addWidget(self.add_password_button)
        self.verticalLayout_7.addWidget(self.new_password_frame)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setMinimumSize(QtCore.QSize(0, 2))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_2.setStyleSheet("background-color:#4F4846;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.scroll_area = QtWidgets.QScrollArea(self.frame_2)
        self.scroll_area.setStyleSheet("border: 0px solid red;")
        self.scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_contents = QtWidgets.QWidget()
        self.scroll_contents.setGeometry(QtCore.QRect(0, 0, 781, 302))
        self.scroll_contents.setObjectName("scroll_contents")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.scroll_contents)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.password_list = QtWidgets.QTableWidget(self.scroll_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_list.sizePolicy().hasHeightForWidth())
        self.password_list.setSizePolicy(sizePolicy)
        self.password_list.setColumnCount(6)
        self.password_list.setObjectName("password_list")
        self.password_list.setRowCount(0)
        self.horizontalLayout_10.addWidget(self.password_list)
        self.scroll_area.setWidget(self.scroll_contents)
        self.verticalLayout_7.addWidget(self.scroll_area)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.stacked_widget.addWidget(self.password_page)
        self.group_page = QtWidgets.QWidget()
        self.group_page.setObjectName("group_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.group_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.group_page)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.title_frame_3 = QtWidgets.QFrame(self.frame_6)
        self.title_frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.title_frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_frame_3.setStyleSheet("background-color:#266150")
        self.title_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame_3.setObjectName("title_frame_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.title_frame_3)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.title_label_3 = QtWidgets.QLabel(self.title_frame_3)
        self.title_label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.title_label_3.setStyleSheet("QLabel {\n"
"    font: bold 30px;\n"
"    color:#FDF8F5;\n"
"    padding-left:6px\n"
"}")
        self.title_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_label_3.setObjectName("title_label_3")
        self.horizontalLayout_17.addWidget(self.title_label_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.verticalLayout_12.addWidget(self.title_frame_3)
        self.line_5 = QtWidgets.QFrame(self.frame_6)
        self.line_5.setMinimumSize(QtCore.QSize(0, 3))
        self.line_5.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line_5.setStyleSheet("background-color:#4F4846;")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_12.addWidget(self.line_5)
        self.frame = QtWidgets.QFrame(self.frame_6)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.add_new_cat_label = QtWidgets.QLabel(self.frame_9)
        self.add_new_cat_label.setStyleSheet("QLabel {\n"
"    font: bold 18px;\n"
"    color:#4F4846;\n"
"}")
        self.add_new_cat_label.setObjectName("add_new_cat_label")
        self.horizontalLayout_15.addWidget(self.add_new_cat_label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem9)
        self.new_category_field = QtWidgets.QLineEdit(self.frame_9)
        self.new_category_field.setStyleSheet("font: 18px")
        self.new_category_field.setObjectName("new_category_field")
        self.horizontalLayout_15.addWidget(self.new_category_field)
        self.new_category_button = QtWidgets.QPushButton(self.frame_9)
        self.new_category_button.setMinimumSize(QtCore.QSize(60, 30))
        self.new_category_button.setMaximumSize(QtCore.QSize(60, 30))
        self.new_category_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}\n"
"")
        self.new_category_button.setObjectName("new_category_button")
        self.horizontalLayout_15.addWidget(self.new_category_button)
        self.verticalLayout_22.addWidget(self.frame_9)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 649, 700))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.category_list = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.category_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.category_list.setLineWidth(0)
        self.category_list.setObjectName("category_list")
        self.verticalLayout_23.addWidget(self.category_list)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_22.addWidget(self.scrollArea)
        self.verticalLayout_12.addWidget(self.frame)
        self.verticalLayout_11.addWidget(self.frame_6)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.stacked_widget.addWidget(self.group_page)
        self.security_page = QtWidgets.QWidget()
        self.security_page.setObjectName("security_page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.security_page)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.security_page)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.title_frame_2 = QtWidgets.QFrame(self.frame_4)
        self.title_frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.title_frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_frame_2.setStyleSheet("background-color:#266150")
        self.title_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame_2.setObjectName("title_frame_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.title_frame_2)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.title_label_2 = QtWidgets.QLabel(self.title_frame_2)
        self.title_label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.title_label_2.setStyleSheet("QLabel {\n"
"    font: bold 30px;\n"
"    color:#FDF8F5;\n"
"    padding-left:6px\n"
"}")
        self.title_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_label_2.setObjectName("title_label_2")
        self.horizontalLayout_16.addWidget(self.title_label_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.verticalLayout_10.addWidget(self.title_frame_2)
        self.line_4 = QtWidgets.QFrame(self.frame_4)
        self.line_4.setMinimumSize(QtCore.QSize(0, 3))
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line_4.setStyleSheet("background-color:#4F4846;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_10.addWidget(self.line_4)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem11)
        self.verticalLayout_9.addWidget(self.frame_4)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.stacked_widget.addWidget(self.security_page)
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.profile_page)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_7 = QtWidgets.QFrame(self.profile_page)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.title_frame_4 = QtWidgets.QFrame(self.frame_8)
        self.title_frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.title_frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_frame_4.setStyleSheet("background-color:#266150")
        self.title_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame_4.setObjectName("title_frame_4")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.title_frame_4)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.title_label_4 = QtWidgets.QLabel(self.title_frame_4)
        self.title_label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.title_label_4.setStyleSheet("QLabel {\n"
"    font: bold 30px;\n"
"    color:#FDF8F5;\n"
"    padding-left:6px\n"
"}")
        self.title_label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_label_4.setObjectName("title_label_4")
        self.horizontalLayout_18.addWidget(self.title_label_4)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem12)
        self.verticalLayout_14.addWidget(self.title_frame_4)
        self.line_6 = QtWidgets.QFrame(self.frame_8)
        self.line_6.setMinimumSize(QtCore.QSize(0, 3))
        self.line_6.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line_6.setStyleSheet("background-color:#4F4846;")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_14.addWidget(self.line_6)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem13)
        self.verticalLayout_13.addWidget(self.frame_8)
        self.verticalLayout_15.addWidget(self.frame_7)
        self.stacked_widget.addWidget(self.profile_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.settings_page)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.settings_frame = QtWidgets.QFrame(self.settings_page)
        self.settings_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.settings_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_frame.setObjectName("settings_frame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.settings_frame)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.settings_frame1 = QtWidgets.QFrame(self.settings_frame)
        self.settings_frame1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.settings_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_frame1.setLineWidth(0)
        self.settings_frame1.setObjectName("settings_frame1")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.settings_frame1)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.title_frame_5 = QtWidgets.QFrame(self.settings_frame1)
        self.title_frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.title_frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_frame_5.setStyleSheet("background-color:#266150")
        self.title_frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame_5.setObjectName("title_frame_5")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.title_frame_5)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.title_label_5 = QtWidgets.QLabel(self.title_frame_5)
        self.title_label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.title_label_5.setStyleSheet("QLabel {\n"
"    font: bold 30px;\n"
"    color:#FDF8F5;\n"
"    padding-left:6px\n"
"}")
        self.title_label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_label_5.setObjectName("title_label_5")
        self.horizontalLayout_19.addWidget(self.title_label_5)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem14)
        self.verticalLayout_17.addWidget(self.title_frame_5)
        self.line_7 = QtWidgets.QFrame(self.settings_frame1)
        self.line_7.setMinimumSize(QtCore.QSize(0, 3))
        self.line_7.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line_7.setStyleSheet("background-color:#4F4846;")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_17.addWidget(self.line_7)
        self.export_frame = QtWidgets.QFrame(self.settings_frame1)
        self.export_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.export_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.export_frame.setObjectName("export_frame")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.export_frame)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.export_frame1 = QtWidgets.QFrame(self.export_frame)
        self.export_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.export_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.export_frame1.setObjectName("export_frame1")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.export_frame1)
        self.horizontalLayout_20.setContentsMargins(-1, -1, 22, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.export_password_label = QtWidgets.QLabel(self.export_frame1)
        self.export_password_label.setStyleSheet("QLabel {\n"
"    font: bold 14px;\n"
"    color:#4F4846;\n"
"}")
        self.export_password_label.setObjectName("export_password_label")
        self.horizontalLayout_20.addWidget(self.export_password_label)
        self.export_button = QtWidgets.QPushButton(self.export_frame1)
        self.export_button.setMinimumSize(QtCore.QSize(120, 30))
        self.export_button.setMaximumSize(QtCore.QSize(120, 30))
        self.export_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}\n"
"")
        self.export_button.setObjectName("export_button")
        self.horizontalLayout_20.addWidget(self.export_button)
        self.verticalLayout_19.addWidget(self.export_frame1)
        self.export_loc_label = QtWidgets.QLabel(self.export_frame)
        self.export_loc_label.setStyleSheet("QLabel {\n"
"    font: bold 12px;\n"
"    color:#4F4846;\n"
"}")
        self.export_loc_label.setObjectName("export_loc_label")
        self.verticalLayout_19.addWidget(self.export_loc_label)
        self.verticalLayout_17.addWidget(self.export_frame)
        self.import_frame = QtWidgets.QFrame(self.settings_frame1)
        self.import_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.import_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.import_frame.setObjectName("import_frame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.import_frame)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.import_frame1 = QtWidgets.QFrame(self.import_frame)
        self.import_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.import_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.import_frame1.setObjectName("import_frame1")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.import_frame1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.import_label = QtWidgets.QLabel(self.import_frame1)
        self.import_label.setStyleSheet("QLabel {\n"
"    font: bold 14px;\n"
"    color:#4F4846;\n"
"}")
        self.import_label.setObjectName("import_label")
        self.verticalLayout_21.addWidget(self.import_label)
        self.import_frame2 = QtWidgets.QFrame(self.import_frame1)
        self.import_frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.import_frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.import_frame2.setObjectName("import_frame2")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.import_frame2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.import_path_label = QtWidgets.QLabel(self.import_frame2)
        self.import_path_label.setStyleSheet("QLabel {\n"
"    font: bold 14px;\n"
"    color:#4F4846;\n"
"}")
        self.import_path_label.setObjectName("import_path_label")
        self.horizontalLayout_21.addWidget(self.import_path_label)
        self.import_field = QtWidgets.QLineEdit(self.import_frame2)
        self.import_field.setObjectName("import_field")
        self.horizontalLayout_21.addWidget(self.import_field)
        self.import_button = QtWidgets.QPushButton(self.import_frame2)
        self.import_button.setMinimumSize(QtCore.QSize(120, 30))
        self.import_button.setMaximumSize(QtCore.QSize(120, 30))
        self.import_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}\n"
"")
        self.import_button.setObjectName("import_button")
        self.horizontalLayout_21.addWidget(self.import_button)
        self.verticalLayout_21.addWidget(self.import_frame2)
        self.verticalLayout_20.addWidget(self.import_frame1)
        self.import_error_label = QtWidgets.QLabel(self.import_frame)
        self.import_error_label.setStyleSheet("QLabel {\n"
"    font: bold 12px;\n"
"    color:#fa9487;\n"
"}")
        self.import_error_label.setObjectName("import_error_label")
        self.verticalLayout_20.addWidget(self.import_error_label)
        self.verticalLayout_17.addWidget(self.import_frame)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem15)
        self.verticalLayout_16.addWidget(self.settings_frame1)
        self.verticalLayout_18.addWidget(self.settings_frame)
        self.stacked_widget.addWidget(self.settings_page)
        self.verticalLayout_2.addWidget(self.stacked_widget)
        self.horizontalLayout.addWidget(self.content_frame)
        main_window.setCentralWidget(self.central_widget)

        self.retranslateUi(main_window)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Password Manager"))
        self.menu_password_button.setText(_translate("main_window", " Passwords"))
        self.menu_group_button.setText(_translate("main_window", " Groups"))
        self.menu_security_button.setText(_translate("main_window", " Security"))
        self.menu_profile_button.setText(_translate("main_window", "Profile"))
        self.menu_settings_button.setText(_translate("main_window", "Settings"))
        self.title_label.setText(_translate("main_window", " Passwords"))
        self.new_password_button.setText(_translate("main_window", "New ▲"))
        self.domain_label.setText(_translate("main_window", "Domain:*"))
        self.account_label.setText(_translate("main_window", "Account Name:"))
        self.url_label.setText(_translate("main_window", "URL: "))
        self.password_label.setText(_translate("main_window", "Password:*"))
        self.p_category_label.setText(_translate("main_window", "Category:"))
        self.add_error_label.setText(_translate("main_window", "*A password with the same domain and account name already exists"))
        self.add_password_button.setText(_translate("main_window", "Add Password"))
        self.password_list.setSortingEnabled(True)
        self.title_label_3.setText(_translate("main_window", "Groups"))
        self.add_new_cat_label.setText(_translate("main_window", "Add new category:"))
        self.new_category_button.setText(_translate("main_window", "Add"))
        self.title_label_2.setText(_translate("main_window", "Security"))
        self.title_label_4.setText(_translate("main_window", "Profile"))
        self.title_label_5.setText(_translate("main_window", "Settings"))
        self.export_password_label.setText(_translate("main_window", "Export passwords to csv file"))
        self.export_button.setText(_translate("main_window", "Download"))
        self.export_loc_label.setText(_translate("main_window", "Downloaded to ./passwords.csv"))
        self.import_label.setText(_translate("main_window", "Import csv file"))
        self.import_path_label.setText(_translate("main_window", "Enter file path:"))
        self.import_button.setText(_translate("main_window", "Import"))
        self.import_error_label.setText(_translate("main_window", "Could not read the specified file. Verify it is a properly formatted csv file."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
