# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/qt_designer/ui_password_field_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(325, 46)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("QFrame {\n"
"background-color:#FDF8F5;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(5, 7, 5, 7)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.password_label = QtWidgets.QPushButton(self.frame)
        self.password_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.password_label.setStyleSheet("QPushButton {\n"
"    color:#4F4846;\n"
"    font: 16px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 5px;\n"
"    background-color:#FDF8F5;\n"
"    text-align: left;\n"
"}\n"
"")
        self.password_label.setObjectName("password_label")
        self.horizontalLayout.addWidget(self.password_label)
        self.copy_button = QtWidgets.QPushButton(self.frame)
        self.copy_button.setMinimumSize(QtCore.QSize(30, 30))
        self.copy_button.setMaximumSize(QtCore.QSize(30, 30))
        self.copy_button.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 15px; border: 0;\n"
" background: none;\n"
" box-shadow: none;\n"
" border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}\n"
"")
        self.copy_button.setText("")
        self.copy_button.setObjectName("copy_button")
        self.horizontalLayout.addWidget(self.copy_button)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.password_label.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
