# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/password_manager_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 726)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuFrame = QtWidgets.QFrame(self.centralwidget)
        self.menuFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.menuFrame.setStyleSheet("QFrame {\n"
"    background-color:#FDF8F5;\n"
"}")
        self.menuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menuFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.menuFrame.setObjectName("menuFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menuFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menuButtonFrame = QtWidgets.QFrame(self.menuFrame)
        self.menuButtonFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.menuButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuButtonFrame.setLineWidth(1)
        self.menuButtonFrame.setObjectName("menuButtonFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menuButtonFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuButton = QtWidgets.QPushButton(self.menuButtonFrame)
        self.menuButton.setMinimumSize(QtCore.QSize(0, 60))
        self.menuButton.setStyleSheet("QPushButton {\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}")
        self.menuButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\Python\Python39\password_manager\src\gui\icons\logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuButton.setIcon(icon)
        self.menuButton.setObjectName("menuButton")
        self.horizontalLayout_2.addWidget(self.menuButton)
        self.verticalLayout.addWidget(self.menuButtonFrame)
        self.menuFrame1 = QtWidgets.QFrame(self.menuFrame)
        self.menuFrame1.setMinimumSize(QtCore.QSize(0, 0))
        self.menuFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuFrame1.setObjectName("menuFrame1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menuFrame1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menuButton1 = QtWidgets.QPushButton(self.menuFrame1)
        self.menuButton1.setMinimumSize(QtCore.QSize(0, 60))
        self.menuButton1.setStyleSheet("QPushButton {\n"
"    color:#FDF8F5;\n"
"    font: bold 20px; border: 0;\n"
" background: none;\n"
" box-shadow: none;\n"
" border-radius: 0px;\n"
"    background-color:#DDAF94;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        self.menuButton1.setFlat(False)
        self.menuButton1.setObjectName("menuButton1")
        self.horizontalLayout_3.addWidget(self.menuButton1)
        self.verticalLayout.addWidget(self.menuFrame1)
        self.menuFrame2 = QtWidgets.QFrame(self.menuFrame)
        self.menuFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuFrame2.setObjectName("menuFrame2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.menuFrame2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menuButton2 = QtWidgets.QPushButton(self.menuFrame2)
        self.menuButton2.setMinimumSize(QtCore.QSize(0, 60))
        self.menuButton2.setStyleSheet("QPushButton {\n"
"    color:#DDAF94;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#FDF8F5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        self.menuButton2.setObjectName("menuButton2")
        self.horizontalLayout_4.addWidget(self.menuButton2)
        self.verticalLayout.addWidget(self.menuFrame2)
        self.menuFrame3 = QtWidgets.QFrame(self.menuFrame)
        self.menuFrame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuFrame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuFrame3.setObjectName("menuFrame3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.menuFrame3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.menuButton3 = QtWidgets.QPushButton(self.menuFrame3)
        self.menuButton3.setMinimumSize(QtCore.QSize(0, 60))
        self.menuButton3.setStyleSheet("QPushButton {\n"
"    color:#DDAF94;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#FDF8F5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        self.menuButton3.setObjectName("menuButton3")
        self.horizontalLayout_5.addWidget(self.menuButton3)
        self.verticalLayout.addWidget(self.menuFrame3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.profileButtonFrame = QtWidgets.QFrame(self.menuFrame)
        self.profileButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profileButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profileButtonFrame.setObjectName("profileButtonFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.profileButtonFrame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.profileButton = QtWidgets.QPushButton(self.profileButtonFrame)
        self.profileButton.setMinimumSize(QtCore.QSize(0, 60))
        self.profileButton.setStyleSheet("QPushButton {\n"
"    color:#DDAF94;\n"
"    font: bold 20px;\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#FDF8F5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#E8CEBF\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/gui\\icons/peple.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profileButton.setIcon(icon1)
        self.profileButton.setObjectName("profileButton")
        self.horizontalLayout_6.addWidget(self.profileButton)
        self.verticalLayout.addWidget(self.profileButtonFrame)
        self.horizontalLayout.addWidget(self.menuFrame)
        self.content_frame = QtWidgets.QFrame(self.centralwidget)
        self.content_frame.setStyleSheet("QFrame {\n"
"    background-color:#FDF8F5;\n"
"}")
        self.content_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.password_page = QtWidgets.QWidget()
        self.password_page.setObjectName("password_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.password_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_frame = QtWidgets.QFrame(self.password_page)
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setStyleSheet("QLabel {\n"
"    font: bold 30px;\n"
"    color:4F4846;\n"
"}")
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_7.addWidget(self.title_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.title_frame)
        self.header_frame = QtWidgets.QFrame(self.password_page)
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.lineEdit = QtWidgets.QLineEdit(self.header_frame)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.header_frame)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton.setStyleSheet("QPushButton {\n"
"     border: 0;\n"
"     background: none;\n"
"     box-shadow: none;\n"
"     border-radius: 0px;\n"
"    background-color:#266150;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#4e9480;\n"
"}")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\Python\Python39\password_manager\src\gui\icons\magnifying_glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.header_frame)
        self.passwordFrame = QtWidgets.QTableWidget(self.password_page)
        self.passwordFrame.setObjectName("passwordFrame")
        self.passwordFrame.setColumnCount(0)
        self.passwordFrame.setRowCount(0)
        self.verticalLayout_3.addWidget(self.passwordFrame)
        self.stackedWidget.addWidget(self.password_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.content_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Manager"))
        self.menuButton1.setText(_translate("MainWindow", "Passwords"))
        self.menuButton2.setText(_translate("MainWindow", "Groups"))
        self.menuButton3.setText(_translate("MainWindow", "Security"))
        self.profileButton.setText(_translate("MainWindow", "Profile"))
        self.title_label.setText(_translate("MainWindow", "Passwords"))